### PR TITLE
Made ImageTag a class + fixed executeAsync

### PR DESCRIPTION
**Pull request by BenjaminUrquhart**
Title.

### CODE REVIEW

**Comment by mattmalec** [comment]
It's not a bug, it's a feature.

**Comment by BenjaminUrquhart** [comment]
That's the spirit

**Comment by komfluent** [comment]
lmfao

**Comment by mattmalec** [comment]
Oh, by the way, asynchronous was working fine. I didn’t have a thread keeping my KSoft4J alive, like JDA. So the process ended before it could be executed. :P

**Comment by BenjaminUrquhart** [comment]
THIS IS ALL YOUR FAULT

**Comment by mattmalec** [comment]
😂😂😂 at least its better now

**Comment by BenjaminUrquhart** [comment]
I just realized I effectively pushed this with the APIException addition. Remind me to switch branches next time.

**Comment by mattmalec** [comment]
well that’s exciting

**Pull request closed without merging**
