### PR TITLE
Started refactoring lyrics

### PR DESCRIPTION
**Pull request by BenjaminUrquhart**
- Lyrics are now in their own separate package.
- Added 3 new objects: Track, Artist, and Album.
- Lyrics are now cached.

TODO:
- Finish ArtistImpl and AlbumImpl
- Clean up TrackImpl
- The ever-needed javadocs

### CODE REVIEW

**Comment by mattmalec** [comment]
I can do the Javadocs

**Comment by BenjaminUrquhart** [comment]
Gonna put this on hold

**Comment by mattmalec** [comment]
sounds good

**Comment by mattmalec** [comment]
I've finished the documentation for the lyrics

**Comment by BenjaminUrquhart** [comment]
Reee you broke the PR by force-pushing

**Comment by mattmalec** [comment]
son of a bitch

**Comment by BenjaminUrquhart** [comment]
Hold up I'm gonna try to force-merge. Be prepared to recommit the async stuff

**Comment by BenjaminUrquhart** [comment]
Wait I have a better idea

**Comment by mattmalec** [comment]
Don’t we have a branch for the lyrics refractor?

**Comment by BenjaminUrquhart** [comment]
Heck I can't merge dev into the branch

**Comment by BenjaminUrquhart** [comment]
WHY GITHUB

**Comment by mattmalec** [comment]
what the fuck happened?

**Pull request merged**
